version: "3.8"

services:
  # API
  backend_server:
    build: ./BackEnd/AI_BackEnd_django
    container_name: ai_backend_k
    image: ai_backend_k:dev
    ports:
      - "7203:8000"

  # FRONTEND
  frontend:
    build: ./FontEnd/Web_face_recognition
    container_name: web_face_recognition_k
    image: web_face_recognition_k:dev
    ports:
      - "7200:3000"
    depends_on:
      - backend_server

  #Websoceket
  websocket:
    build: ./WebSocket
    container_name: web_socket_k
    image: web_socket_k:dev
    ports:
      - "7204:8765"
    depends_on:
      - frontend

  #PhpmyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  #db
  db_k:
    build: ./Database
    container_name: db_k
    image: sql_k:dev
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: database
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - aidetect-data-volumes:/usr/local/bin/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"

volumes:
  aidetect-data-volumes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\Kong\Work\Ai_work\Database\data