# Generated by Django 4.1.13 on 2024-02-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_name_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.AlterModelTable(
            name='user',
            table='admin',
        ),
    ]
