# Generated by Django 4.1.13 on 2024-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_user_name_rename_password_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
