# Generated by Django 4.1.13 on 2024-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_admin_remove_user_name_remove_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_text', models.CharField(default='unknow', max_length=255)),
                ('mood_type', models.CharField(default='unknow', max_length=255)),
            ],
            options={
                'db_table': 'Text_mood',
            },
        ),
        migrations.CreateModel(
            name='type_mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(default='unknow', max_length=255)),
                ('mood_type_path', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Type_mood',
            },
        ),
    ]
