# Generated by Django 4.1.13 on 2024-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_face_detect'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TH_name', models.CharField(default='unknow', max_length=255)),
                ('Eng_name', models.CharField(default='unknow', max_length=255)),
                ('Folder_img_path', models.CharField(default='/', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
